# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swarm.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'swarm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswarm.proto\x12\x08swarm.v1\"-\n\nRunRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\"_\n\x0bRunResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61\x63hed\x18\x02 \x01(\x08\x12\x14\n\x0c\x61\x63tive_agent\x18\x03 \x01(\t\x12\x0e\n\x06tokens\x18\x04 \x01(\x05\x12\x0c\n\x04mode\x18\x05 \x01(\t\"-\n\rRecallRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"4\n\tMemoryHit\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"3\n\x0eRecallResponse\x12!\n\x04hits\x18\x01 \x03(\x0b\x32\x13.swarm.v1.MemoryHit2\x7f\n\x0cSwarmService\x12\x32\n\x03Run\x12\x14.swarm.v1.RunRequest\x1a\x15.swarm.v1.RunResponse\x12;\n\x06Recall\x12\x17.swarm.v1.RecallRequest\x1a\x18.swarm.v1.RecallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swarm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=25
  _globals['_RUNREQUEST']._serialized_end=70
  _globals['_RUNRESPONSE']._serialized_start=72
  _globals['_RUNRESPONSE']._serialized_end=167
  _globals['_RECALLREQUEST']._serialized_start=169
  _globals['_RECALLREQUEST']._serialized_end=214
  _globals['_MEMORYHIT']._serialized_start=216
  _globals['_MEMORYHIT']._serialized_end=268
  _globals['_RECALLRESPONSE']._serialized_start=270
  _globals['_RECALLRESPONSE']._serialized_end=321
  _globals['_SWARMSERVICE']._serialized_start=323
  _globals['_SWARMSERVICE']._serialized_end=450
# @@protoc_insertion_point(module_scope)
